Breaking Change Dependency Error
Rich and Click versions cause cstools to fail. Any new installation of cs tools it will give the error TypeError: Directory.get_metavar() got an unexpected keyword argument 'ctx'

https: //github.com/fastapi/typer/discussions/1215
Co-Authored-By: saurabhsingh2974 <164007629+saurabhsingh2974@users.noreply.github.com>